version: '3.8'

services:
  skinwatcher:
    build: 
      context: .
      dockerfile: Dockerfile
    image: docker.io/skinwatcher_skinwatcher:latest
    container_name: skinwatcher
    volumes:
      - type: bind
        source: ./config
        target: /app/config
    env_file:
      - ./.env
    restart: unless-stopped